CREATE TABLE IF NOT EXISTS roles (
  id   IDENTITY PRIMARY KEY,
  name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id       IDENTITY PRIMARY KEY,
  login    VARCHAR(64) UNIQUE NOT NULL,
  password VARCHAR(64) NOT NULL,
  email VARCHAR(64) UNIQUE NOT NULL,
  firstName VARCHAR(64),
  lastName VARCHAR(64),
  birthday DATE  NOT NULL,
  roles_id     BIGINT    NOT NULL,
  FOREIGN KEY (roles_id) REFERENCES roles (id)
);